export const userData = [
  {
    id: 1,
    name: "Lorem ipsum",
    position: "Developer",
    age: 28,
    email: "lorem.ipsum@mail.com",
    password: "sjkadhjakdh",
    image: "/assets/img/profile-img.jpg",
    gender: "female",
    address:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A, nisi excepturi odit voluptatem dolor expedita nulla dignissimos qui labore quasi? Voluptatum non dolores facere recusandae quod, vero nihil perspiciatis cupiditate",
    city: "Ny",
    state: "DC",
    startDate: "2020-12-05",
    salary: 25000,
    terms: true,
  },
  {
    id: 2,
    name: "Mr. Anderson",
    position: "Developer",
    age: 28,
    email: "lorem.ipsum@mail.com",
    password: "sjkadhjakdh",
    image: "/assets/img/profile-img.jpg",
    gender: "male",
    address:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A, nisi excepturi odit voluptatem dolor expedita nulla dignissimos qui labore quasi? Voluptatum non dolores facere recusandae quod, vero nihil perspiciatis cupiditate",
    city: "Ny",
    state: "Oregon",
    startDate: "2012-03-22",
    salary: 25000,
    terms: true,
  },
  {
    id: 3,
    name: "Kevin Anderson",
    position: "Developer",
    age: 28,
    email: "lorem.ipsum@mail.com",
    password: "sjkadhjakdh",
    image: "/assets/img/profile-img.jpg",
    gender: "male",
    address:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. A, nisi excepturi odit voluptatem dolor expedita nulla dignissimos qui labore quasi? Voluptatum non dolores facere recusandae quod, vero nihil perspiciatis cupiditate",
    city: "Ny",
    state: "DC",
    startDate: "2018-01-31",
    salary: 25000,
    terms: true,
  },
]
